import type {
  Activity,
  DemoUser,
  DocumentItem,
  Message,
  Project,
  Quotation,
  Shipment,
  ShipmentHistory,
} from "./types";

export const demoUsers: DemoUser[] = [
  {
    id: 1,
    name: "Internal User",
    email: "admin@demo.pl",
    password: "admin123",
    role: "admin",
    company: "Internal Team",
    position: "Administrator",
  },
  {
    id: 2,
    name: "Hansen Project Team",
    email: "projects@hansenpolska.eu",
    password: "hansen123",
    role: "supplier",
    company: "Hansen Polska",
    position: "Supplier",
  },
];

export const initialProjects: Project[] = [
  {
    id: 1,
    name: "Hotel Saski Warszawa",
    client: "ALUme Sp. z o.o.",
    city: "Warszawa",
    country: "Poland",
    reference: "HSW-DEMO-01",
    supplier: "Hansen",
    status: "Quotation",
    value: 393166.51,
    currency: "EUR",
    units: 529,
    area: 3319.74,
    system: "Hansen Millennium",
    owner: "Internal Team",
    description:
      "Demo workspace for the Hotel Saski Warszawa project. Architectural files, facade details and a sample Hansen commercial proposal are being reviewed together.",
    createdAt: "2026-07-16",
    updatedAt: "2026-08-17",
  },
  {
    id: 6,
    name: "EC 1 Łódź",
    client: "ALUme Sp. z o.o.",
    city: "Łódź",
    country: "Poland",
    reference: "EC1-DEMO-02",
    supplier: "Hansen",
    status: "Quotation",
    value: 1227000,
    currency: "EUR",
    units: 1476,
    area: 0,
    system: "Aluprof aluminium systems",
    owner: "Internal Team",
    description:
      "Demo facade and aluminium joinery package for EC 1 Łódź. The commercial values, quantities and revisions shown in this workspace are illustrative.",
    createdAt: "2026-08-05",
    updatedAt: "2026-08-17",
  },
  {
    id: 7,
    name: "Cactus Tower Copenhagen",
    client: "ALUme Sp. z o.o.",
    city: "Copenhagen",
    country: "Denmark",
    reference: "CTC-DEMO-03",
    supplier: "Hansen",
    status: "Quotation",
    value: 396396.69,
    currency: "USD",
    units: 514,
    area: 1922.32,
    system: "Hansen Millennium",
    owner: "Internal Team",
    description:
      "Demo facade package for Cactus Tower Copenhagen. The workspace contains illustrative drawings, schedules and commercial documentation for presentation purposes.",
    createdAt: "2026-08-07",
    updatedAt: "2026-08-17",
  },
  {
    id: 2,
    name: "Green Park Residence",
    client: "Nova Development",
    city: "Kraków",
    country: "Poland",
    reference: "GPR-26",
    supplier: "Hansen",
    status: "Technical Review",
    value: 184750,
    currency: "EUR",
    units: 218,
    area: 1285.4,
    system: "Hansen Millennium",
    owner: "Internal Team",
    description:
      "Residential project under technical review. The latest facade package and glazing requirements are waiting for supplier confirmation.",
    createdAt: "2026-08-03",
    updatedAt: "2026-08-17",
  },
  {
    id: 3,
    name: "Nova II",
    client: "Vistula Homes",
    city: "Warsaw",
    country: "Poland",
    reference: "NV2-WAW",
    supplier: "Hansen",
    status: "Contract",
    value: 212400,
    currency: "EUR",
    units: 181,
    area: 1042.8,
    system: "Hansen Millennium",
    owner: "Internal Team",
    description:
      "Commercial conditions accepted. The project is waiting for final contract confirmation and production release.",
    createdAt: "2026-07-21",
    updatedAt: "2026-08-16",
  },
  {
    id: 4,
    name: "City Point",
    client: "Prime Estates",
    city: "Łódź",
    country: "Poland",
    reference: "CP-LOD-04",
    supplier: "Hansen",
    status: "Shipping",
    value: 148900,
    currency: "EUR",
    units: 119,
    area: 718.2,
    system: "Hansen Millennium",
    owner: "Internal Team",
    description:
      "Production is complete and the shipment is on the way to the construction site in Łódź.",
    createdAt: "2026-06-29",
    updatedAt: "2026-08-17",
  },
  {
    id: 5,
    name: "Marina Quarter",
    client: "Baltic Development",
    city: "Gdynia",
    country: "Poland",
    reference: "MQ-GDY-01",
    supplier: "Hansen",
    status: "Inquiry",
    value: 126500,
    currency: "EUR",
    units: 96,
    area: 604.7,
    system: "Hansen Millennium",
    owner: "Internal Team",
    description:
      "New inquiry. Initial architectural documents have been received and await technical classification.",
    createdAt: "2026-08-15",
    updatedAt: "2026-08-17",
  },
];

export const initialDocuments: DocumentItem[] = [
  // HOTEL SASKI WARSZAWA
  {
    id: 1,
    projectId: 1,
    name: "Hansen_Hotel_Saski_Oferta_DEMO_R01.pdf",
    category: "Quotation",
    fileType: "PDF",
    folder: "Hansen / Quotation",
    status: "Reviewed",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "17 Aug 2026",
    previewUrl: "/demo/palio/palio-quotation.pdf",
  },
  {
    id: 2,
    projectId: 1,
    name: "Hotel_Saski_Zestawienie_Stolarki_DEMO_R03.pdf",
    category: "Window schedule",
    fileType: "PDF",
    folder: "Architecture / Window schedules",
    status: "Reviewed",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "16 Aug 2026",
    previewUrl: "/demo/palio/palio-window-schedule.pdf",
  },
  {
    id: 3,
    projectId: 1,
    name: "Hotel_Saski_Raport_Akustyczny_DEMO.pdf",
    category: "Acoustics",
    fileType: "PDF",
    folder: "Hansen / Acoustics",
    status: "Needs review",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "17 Aug 2026",
    previewUrl: "/demo/palio/palio-acoustic-40-45db.pdf",
  },
  {
    id: 4,
    projectId: 1,
    name: "Hansen_Millennium_Karta_Systemowa_DEMO.pdf",
    category: "Technical",
    fileType: "PDF",
    folder: "Hansen / Technical",
    status: "Available",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "17 Aug 2026",
  },
  {
    id: 5,
    projectId: 1,
    name: "Uw calculation.zip",
    category: "Calculation",
    fileType: "ZIP",
    folder: "Hansen / Calculations",
    status: "Reviewed",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "17 Aug 2026",
  },

  // EC 1 LODZ — demo package
  {
    id: 20,
    projectId: 6,
    name: "EC1_Lodz_Zestawienie_Stolarki_DEMO_R02.pdf",
    category: "Window schedule",
    fileType: "PDF",
    folder: "Architecture / Window schedule",
    status: "Reviewed",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/opolska/window-schedule.pdf",
  },
  {
    id: 21,
    projectId: 6,
    name: "Nawiewnik_Karta_Techniczna.pdf",
    category: "Technical",
    fileType: "PDF",
    folder: "Architecture / Technical datasheets",
    status: "Available",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/opolska/brookvent-aquvent.pdf",
  },
  {
    id: 22,
    projectId: 6,
    name: "Lacznik_95mm_Instrukcja_Montazu.pdf",
    category: "Technical",
    fileType: "PDF",
    folder: "Architecture / Technical details",
    status: "Available",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/opolska/connector-instruction.pdf",
  },
  {
    id: 23,
    projectId: 6,
    name: "Reference image.png",
    category: "Other",
    fileType: "PNG",
    folder: "Architecture / Reference",
    status: "Available",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/opolska/reference-image.png",
  },
  {
    id: 24,
    projectId: 6,
    name: "Hansen_EC1_Rysunek_Projektowy_DEMO_R02.pdf",
    category: "Technical",
    fileType: "PDF",
    folder: "Hansen / Project drawing",
    status: "Reviewed",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/opolska/hansen-project-drawing.pdf",
  },
  {
    id: 25,
    projectId: 6,
    name: "Hansen_EC1_Oferta_DEMO_R02.pdf",
    category: "Quotation",
    fileType: "PDF",
    folder: "Hansen / Quotation",
    status: "Needs review",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/opolska/hansen-offer-r02.pdf",
  },
  {
    id: 26,
    projectId: 6,
    name: "Hansen_Detal_Systemowy_HS76.pdf",
    category: "Technical",
    fileType: "PDF",
    folder: "Hansen / System detail",
    status: "Reviewed",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/opolska/hansen-system-detail.pdf",
  },
  {
    id: 27,
    projectId: 6,
    name: "Hansen_EC1_Pakiet_DEMO.zip",
    category: "Quotation",
    fileType: "ZIP",
    folder: "Hansen / Source package",
    status: "Available",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/opolska/hansen-offer-package.zip",
  },

  // CACTUS TOWER COPENHAGEN — demo package
  {
    id: 30,
    projectId: 7,
    name: "Cactus_Tower_Rysunki_Architektoniczne_DEMO_R03.pdf",
    category: "Architecture",
    fileType: "PDF",
    folder: "Architecture / Drawings",
    status: "Reviewed",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/crescent/architectural-drawings.pdf",
  },
  {
    id: 31,
    projectId: 7,
    name: "Cactus_Tower_Takeoff_DEMO_R02.pdf",
    category: "Window schedule",
    fileType: "PDF",
    folder: "Architecture / Takeoff",
    status: "Reviewed",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/crescent/takeoff-summary.pdf",
  },
  {
    id: 32,
    projectId: 7,
    name: "Glass_Etch_Datasheet_EN.pdf",
    category: "Technical",
    fileType: "PDF",
    folder: "Architecture / Glass datasheets",
    status: "Available",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/crescent/4bird-etch-datasheet.pdf",
  },
  {
    id: 33,
    projectId: 7,
    name: "Laminated_Glass_Datasheet_EN.pdf",
    category: "Technical",
    fileType: "PDF",
    folder: "Architecture / Glass datasheets",
    status: "Available",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/crescent/4bird-lami-datasheet.pdf",
  },
  {
    id: 34,
    projectId: 7,
    name: "Cactus_Tower_Project_Scope_DEMO.pdf",
    category: "Architecture",
    fileType: "PDF",
    folder: "Architecture / Scope",
    status: "Reviewed",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/crescent/crescent-scope.pdf",
  },
  {
    id: 35,
    projectId: 7,
    name: "Hansen_Cactus_Tower_Position_Drawing_DEMO_R02.pdf",
    category: "Technical",
    fileType: "PDF",
    folder: "Hansen / Position drawing",
    status: "Reviewed",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/crescent/hansen-position-drawing.pdf",
  },
  {
    id: 36,
    projectId: 7,
    name: "Hansen_Cactus_Tower_Quotation_DEMO_R02.pdf",
    category: "Quotation",
    fileType: "PDF",
    folder: "Hansen / Quotation",
    status: "Needs review",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/crescent/hansen-quotation.pdf",
  },
  {
    id: 37,
    projectId: 7,
    name: "Hansen_Cactus_Tower_Correspondence_DEMO.msg",
    category: "Communication",
    fileType: "MSG",
    folder: "Hansen / Communication",
    status: "Available",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "13 Aug 2026",
    previewUrl: "/demo/crescent/supplier-correspondence.msg",
  },

  // Additional demo pipeline projects
  {
    id: 40,
    projectId: 2,
    name: "Facade Revision 04.pdf",
    category: "Architecture",
    fileType: "PDF",
    folder: "Architecture",
    status: "Needs review",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "17 Aug 2026",
  },
  {
    id: 41,
    projectId: 2,
    name: "Glazing Schedule v2.pdf",
    category: "Window schedule",
    fileType: "PDF",
    folder: "Technical",
    status: "Needs review",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "17 Aug 2026",
  },
  {
    id: 42,
    projectId: 3,
    name: "Commercial Package v2.pdf",
    category: "Quotation",
    fileType: "PDF",
    folder: "Commercial",
    status: "Reviewed",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "16 Aug 2026",
  },
  {
    id: 43,
    projectId: 4,
    name: "Delivery Documentation.pdf",
    category: "Technical",
    fileType: "PDF",
    folder: "Shipping",
    status: "Reviewed",
    source: "Hansen",
    uploadedBy: "Hansen Project Team",
    uploadedAt: "17 Aug 2026",
  },
  {
    id: 44,
    projectId: 5,
    name: "Initial architectural package.pdf",
    category: "Architecture",
    fileType: "PDF",
    folder: "Architecture",
    status: "Available",
    source: "Internal Team",
    uploadedBy: "Internal User",
    uploadedAt: "17 Aug 2026",
  },
];

export const initialQuotations: Quotation[] = [
  {
    id: 1,
    projectId: 1,
    number: "10,657/2",
    date: "21 Jul 2026",
    amount: 393166.51,
    currency: "EUR",
    status: "Under review",
    leadTime: "6–7 weeks following order confirmation",
    deliveryTerms: "EXW — Sakarya / Akyazi, Turkey",
    validity: "5 days from issue date",
    profileSystem: "Inova 76",
    hardware: "ROTO",
    securityLevel: "RC1",
  },
  {
    id: 5,
    projectId: 6,
    number: "Q26UC-269 / Rv.-1",
    date: "5 Aug 2026",
    amount: 1227000,
    currency: "EUR",
    status: "Under review",
    leadTime: "To be confirmed",
    deliveryTerms: "DAP — Poland (€1,150,000 EXW + €77,000 transport)",
    validity: "Valid until 12 Aug 2026",
    profileSystem: "Aluprof aluminium systems / DEMO",
    hardware: "Giesse",
    securityLevel: "Not specified",
  },
  {
    id: 6,
    projectId: 7,
    number: "10,680/1",
    date: "7 Aug 2026",
    amount: 396396.69,
    currency: "USD",
    status: "Under review",
    leadTime: "4–6 weeks following order confirmation",
    deliveryTerms: "EXW — Sakarya / Akyazi, Turkey",
    validity: "5 days from issue date",
    profileSystem: "Hansen Unital / DEMO",
    hardware: "ROTO / G-U SDR 4\" limiter",
    securityLevel: "Fully Security",
  },
  {
    id: 2,
    projectId: 2,
    number: "Q-2026-0821",
    date: "14 Aug 2026",
    amount: 184750,
    currency: "EUR",
    status: "Draft",
    leadTime: "6–7 weeks",
    deliveryTerms: "DAP Kraków",
    validity: "7 days",
    profileSystem: "Inova 76",
    hardware: "ROTO",
    securityLevel: "RC1",
  },
  {
    id: 3,
    projectId: 3,
    number: "Q-2026-0719",
    date: "30 Jul 2026",
    amount: 212400,
    currency: "EUR",
    status: "Approved",
    leadTime: "7 weeks",
    deliveryTerms: "DAP Warsaw",
    validity: "7 days",
    profileSystem: "Inova 76",
    hardware: "ROTO",
    securityLevel: "RC1",
  },
  {
    id: 4,
    projectId: 4,
    number: "Q-2026-0618",
    date: "19 Jun 2026",
    amount: 148900,
    currency: "EUR",
    status: "Approved",
    leadTime: "6 weeks",
    deliveryTerms: "DAP Łódź",
    validity: "7 days",
    profileSystem: "Inova 76",
    hardware: "ROTO",
    securityLevel: "RC1",
  },
];

export const initialShipments: Shipment[] = [
  {
    id: 1,
    projectId: 1,
    status: "Planning",
    plannedDispatch: "",
    eta: "",
    carrier: "",
    trackingNumber: "",
    deliveryAddress: "Gdańsk, Poland",
    notes: "Shipping planning will begin after final technical and commercial approval.",
    progress: 20,
    updatedBy: "Internal User",
    updatedAt: "17 Aug 2026, 13:40",
  },
  {
    id: 4,
    projectId: 6,
    status: "Planning",
    plannedDispatch: "",
    eta: "",
    carrier: "",
    trackingNumber: "",
    deliveryAddress: "Katowice, Poland",
    notes: "Current commercial option is DAP Poland. The offer includes €77,000 transport; dispatch dates are not confirmed yet.",
    progress: 20,
    updatedBy: "Internal User",
    updatedAt: "17 Aug 2026, 14:05",
  },
  {
    id: 5,
    projectId: 7,
    status: "Planning",
    plannedDispatch: "",
    eta: "",
    carrier: "",
    trackingNumber: "",
    deliveryAddress: "Copenhagen, Denmark",
    notes: "Quotation is EXW Sakarya / Akyazi. International logistics have not been scheduled yet.",
    progress: 20,
    updatedBy: "Internal User",
    updatedAt: "17 Aug 2026, 14:12",
  },
  {
    id: 2,
    projectId: 3,
    status: "Production",
    plannedDispatch: "2026-09-21",
    eta: "2026-09-28",
    carrier: "",
    trackingNumber: "",
    deliveryAddress: "Warsaw, Poland",
    notes: "Production schedule confirmed.",
    progress: 55,
    updatedBy: "Hansen Project Team",
    updatedAt: "16 Aug 2026, 15:10",
  },
  {
    id: 3,
    projectId: 4,
    status: "In transit",
    plannedDispatch: "2026-08-16",
    eta: "2026-08-20",
    carrier: "TransGlobal Logistics",
    trackingNumber: "TR-ASA-260816-04",
    deliveryAddress: "Łódź, Poland",
    notes: "Truck departed from the factory. Delivery window expected between 09:00–13:00.",
    progress: 90,
    updatedBy: "Hansen Project Team",
    updatedAt: "17 Aug 2026, 09:21",
  },
];

export const initialShipmentHistory: ShipmentHistory[] = [
  {
    id: 1,
    shipmentId: 3,
    field: "Status",
    oldValue: "Ready",
    newValue: "In transit",
    changedBy: "Hansen Project Team",
    changedAt: "17 Aug 2026, 09:21",
  },
  {
    id: 2,
    shipmentId: 3,
    field: "Tracking number",
    oldValue: "—",
    newValue: "TR-ASA-260816-04",
    changedBy: "Hansen Project Team",
    changedAt: "17 Aug 2026, 09:22",
  },
  {
    id: 3,
    shipmentId: 4,
    field: "Shipment",
    oldValue: "—",
    newValue: "Planning created",
    changedBy: "Internal User",
    changedAt: "17 Aug 2026, 14:05",
  },
  {
    id: 4,
    shipmentId: 5,
    field: "Shipment",
    oldValue: "—",
    newValue: "Planning created",
    changedBy: "Internal User",
    changedAt: "17 Aug 2026, 14:12",
  },
];

export const initialMessages: Message[] = [
  {
    id: 1,
    projectId: 1,
    authorRole: "admin",
    author: "Internal User",
    text: "The demo architectural package for Hotel Saski Warszawa is now available for review.",
    createdAt: "09:12",
  },
  {
    id: 2,
    projectId: 1,
    authorRole: "supplier",
    author: "Hansen Project Team",
    text: "Quotation 10,657/2 and the acoustic performance documentation have been uploaded.",
    createdAt: "09:28",
  },
  {
    id: 3,
    projectId: 1,
    authorRole: "admin",
    author: "Internal User",
    text: "Thank you. We are reviewing the acoustic requirements for the selected positions.",
    createdAt: "10:05",
  },
  {
    id: 20,
    projectId: 6,
    authorRole: "admin",
    author: "Internal User",
    text: "The EC 1 Łódź demo schedule and technical documentation have been added to the workspace.",
    createdAt: "10:18",
  },
  {
    id: 21,
    projectId: 6,
    authorRole: "supplier",
    author: "Hansen Project Team",
    text: "Revision 1 of the EC 1 Łódź demo commercial offer is uploaded for presentation.",
    createdAt: "10:34",
  },
  {
    id: 22,
    projectId: 6,
    authorRole: "admin",
    author: "Internal User",
    text: "Received. We will review the DAP total and the transport component before the next commercial step.",
    createdAt: "10:48",
  },
  {
    id: 30,
    projectId: 7,
    authorRole: "admin",
    author: "Internal User",
    text: "The Cactus Tower Copenhagen demo drawings, scope and takeoff summary are available for review.",
    createdAt: "11:06",
  },
  {
    id: 31,
    projectId: 7,
    authorRole: "supplier",
    author: "Hansen Project Team",
    text: "Quotation 10,680/1 and the position drawing are uploaded. Current total is 514 units / 1,922.32 m², EXW Sakarya.",
    createdAt: "11:24",
  },
  {
    id: 4,
    projectId: 4,
    authorRole: "supplier",
    author: "Hansen Project Team",
    text: "The City Point shipment has departed. Tracking information has been updated.",
    createdAt: "11:18",
  },
];

export const initialActivities: Activity[] = [
  {
    id: 10,
    projectId: 6,
    title: "EC 1 demo package completed",
    description: "The complete uploaded architecture and Hansen package has been added to the project workspace.",
    createdBy: "Internal User",
    createdAt: "17 Aug · 14:20",
  },
  {
    id: 11,
    projectId: 6,
    title: "Revision 1 quotation added",
    description: "Q26UC-269 / Rv.-1 added: 1,476 units, €1,227,000 DAP total.",
    createdBy: "Hansen Project Team",
    createdAt: "17 Aug · 14:18",
  },
  {
    id: 12,
    projectId: 7,
    title: "Cactus Tower demo package completed",
    description: "Architecture, takeoff, glass datasheets, Hansen drawing, quotation and correspondence were added.",
    createdBy: "Internal User",
    createdAt: "17 Aug · 14:16",
  },
  {
    id: 13,
    projectId: 7,
    title: "Hansen quotation added",
    description: "Quotation 10,680/1 added: 514 units, 1,922.32 m², $396,396.69 EXW total.",
    createdBy: "Hansen Project Team",
    createdAt: "17 Aug · 14:14",
  },
  {
    id: 1,
    projectId: 1,
    title: "Quotation uploaded",
    description: "A demo quotation was added to Hotel Saski Warszawa.",
    createdBy: "Hansen Project Team",
    createdAt: "17 Aug · 09:28",
  },
  {
    id: 2,
    projectId: 1,
    title: "Acoustic documents updated",
    description: "A 40–45 dB performance report was added for review.",
    createdBy: "Hansen Project Team",
    createdAt: "17 Aug · 09:32",
  },
  {
    id: 3,
    projectId: 2,
    title: "New revision received",
    description: "Facade Revision 04 was uploaded for technical verification.",
    createdBy: "Internal User",
    createdAt: "17 Aug · 10:02",
  },
  {
    id: 4,
    projectId: 4,
    title: "Shipment departed",
    description: "City Point shipment status changed to In transit.",
    createdBy: "Hansen Project Team",
    createdAt: "17 Aug · 09:21",
  },
  {
    id: 5,
    projectId: 5,
    title: "Inquiry created",
    description: "Marina Quarter was added to the project pipeline.",
    createdBy: "Internal User",
    createdAt: "17 Aug · 08:45",
  },
];
